//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationMenu
    {
        public string SysId { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Hint { get; set; }
        public string Desciption { get; set; }
        public Nullable<int> OrderSQ { get; set; }
        public string Roles { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> Active { get; set; }
        public string Controller { get; set; }
        public string ImageIcon { get; set; }
    }
}
