//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRule
    {
        public string SysId { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> Active { get; set; }
        public string TableRef { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string ColumnName { get; set; }
        public string ColumnLabel { get; set; }
        public Nullable<int> OrderSQ { get; set; }
    }
}
