//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_MVC5Bootstrap_Intellivue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdviser
    {
        public string AdviserNo { get; set; }
        public string ParentAdviserNo { get; set; }
        public string AdviserType { get; set; }
        public string AdviserName { get; set; }
        public string StatusFlag { get; set; }
        public string AdviserGroupNo { get; set; }
        public string HasChildNode { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string EmailAddr1 { get; set; }
        public string EmailAddr2 { get; set; }
        public string Addrline1 { get; set; }
        public string Addrline2 { get; set; }
        public string Addrline3 { get; set; }
        public string Addrline4 { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string CountryCode { get; set; }
        public string MailingName { get; set; }
        public string CorrName { get; set; }
        public string ILGN { get; set; }
        public string FileNote { get; set; }
        public string BankBSB { get; set; }
        public string BankAcctNo { get; set; }
        public string BankAcctName { get; set; }
        public string DealerLicense { get; set; }
        public string WorkTel { get; set; }
        public string WorkFax { get; set; }
        public Nullable<System.DateTime> LastChangedDate { get; set; }
        public string Mobile { get; set; }
        public string ABN { get; set; }
        public string LicenceNo { get; set; }
        public string RCTIFlag { get; set; }
        public Nullable<System.DateTime> RCTIDate { get; set; }
        public string ClientNotification { get; set; }
        public string ClientNotificationAtGroup { get; set; }
        public string DirectMarketingFlag { get; set; }
        public string PaymentMethod { get; set; }
        public string RebateTrailFlag { get; set; }
        public string TrailPayable { get; set; }
        public string CommPayable { get; set; }
        public string UserID { get; set; }
        public string ExtRef1 { get; set; }
        public string ExtRef2 { get; set; }
        public string ExtRef3 { get; set; }
        public string ReportState { get; set; }
        public string pAddrLine1 { get; set; }
        public string pAddrLine2 { get; set; }
        public string pAddrLine3 { get; set; }
        public string pSuburb { get; set; }
        public string pState { get; set; }
        public string pPostcode { get; set; }
        public string pCountryCode { get; set; }
        public string AdviserRef { get; set; }
        public string Agent { get; set; }
        public Nullable<decimal> RebatePerc { get; set; }
        public Nullable<System.DateTime> LastStmtDate { get; set; }
        public Nullable<int> LastStmtNo { get; set; }
        public Nullable<decimal> LastPymtAmt { get; set; }
        public string LastPymtWithheldFlag { get; set; }
        public string WithheldReason { get; set; }
        public Nullable<decimal> DialUpCommPerc { get; set; }
        public Nullable<System.DateTime> ABNDate { get; set; }
        public Nullable<System.DateTime> LicenceDate { get; set; }
        public Nullable<int> AllowASF { get; set; }
        public string AFSL { get; set; }
        public string CRef { get; set; }
        public string DPIDCode { get; set; }
        public string CCFirstName { get; set; }
        public string CCLastName { get; set; }
        public Nullable<decimal> UpfrontPerc { get; set; }
        public Nullable<decimal> UpfrontCFSGPerc { get; set; }
        public Nullable<decimal> TrailPerc { get; set; }
        public Nullable<decimal> TrailCFSGPerc { get; set; }
        public string GSTReg { get; set; }
        public Nullable<System.DateTime> GSTRegDate { get; set; }
        public string DealerType { get; set; }
        public string DealerSubType { get; set; }
        public string RptfreqFUM { get; set; }
        public string RptfreqIL { get; set; }
        public string RptfreqACC { get; set; }
        public string RptfreqTL { get; set; }
        public string DeliveryFUM { get; set; }
        public string DeliveryIL { get; set; }
        public string DeliveryACC { get; set; }
        public string DeliveryTL { get; set; }
        public string LastSentFUM { get; set; }
        public string LastSentIL { get; set; }
        public string LastSentACC { get; set; }
        public string LastSentTL { get; set; }
        public string InvLinkFullExtract { get; set; }
        public string BrokerageStmDelivery { get; set; }
        public string BrokStmtFormat { get; set; }
        public string BrokReport { get; set; }
        public string TradingAs { get; set; }
    }
}
