//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_MVC5Bootstrap_Intellivue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public string OfficePersonCode { get; set; }
        public string BlockCode { get; set; }
        public string AcctNo { get; set; }
        public int ProdNo { get; set; }
        public string StatusFlag { get; set; }
        public string ResidentCode { get; set; }
        public string ResidentCountryCode { get; set; }
        public string AcctType { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string EmailAddr1 { get; set; }
        public string EmailAddr2 { get; set; }
        public string Addrline1 { get; set; }
        public string Addrline2 { get; set; }
        public string Addrline3 { get; set; }
        public string Addrline4 { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string CountryCode { get; set; }
        public string MailingName { get; set; }
        public string CorrName { get; set; }
        public string ILCN { get; set; }
        public string LenderNo { get; set; }
        public string AdvGroupCode { get; set; }
        public string FileNote { get; set; }
        public string BankID { get; set; }
        public string BankBSB { get; set; }
        public string BankAcctNo { get; set; }
        public string BankAcctName { get; set; }
        public string BankAddr { get; set; }
        public string TelWithdrawal { get; set; }
        public string TFNRule { get; set; }
        public string ABN { get; set; }
        public Nullable<System.DateTime> DateLastChanged { get; set; }
        public string AcctName { get; set; }
        public string AcctSortingName { get; set; }
        public string CCAdviserFlag { get; set; }
        public string TaxExempt { get; set; }
        public string TaxExemptCode { get; set; }
        public Nullable<System.DateTime> ChildDOB { get; set; }
        public string TelSwitching { get; set; }
        public string TelDeposit { get; set; }
        public string Consent { get; set; }
        public string ExternalNo1 { get; set; }
        public string ExternalNo2 { get; set; }
        public string ACN { get; set; }
        public string PIN { get; set; }
        public Nullable<System.DateTime> PINPostedDate { get; set; }
        public string PINFlag { get; set; }
        public string TempPIN { get; set; }
        public string TempTrustee { get; set; }
        public string TempABN { get; set; }
        public string WorkFax { get; set; }
        public string CorrMethod { get; set; }
        public string ExmptTaxSec128B { get; set; }
        public string TrusteeCapacity { get; set; }
        public string ExmptOtherIncomeTaxSec23 { get; set; }
        public string ExmptOtherIncomeIntOrg { get; set; }
        public Nullable<System.DateTime> NonResidentFromDate { get; set; }
        public Nullable<System.DateTime> NonResidentToDate { get; set; }
        public string InterfundAcctFlag { get; set; }
        public Nullable<int> InterfundAcctprodNo { get; set; }
        public Nullable<int> NoPin { get; set; }
        public Nullable<long> LastDocNo { get; set; }
        public Nullable<decimal> ASFFee { get; set; }
        public Nullable<decimal> ASFRate { get; set; }
        public string ChequeBookReq { get; set; }
        public string DepositBookReq { get; set; }
        public string DebitCardReq { get; set; }
        public Nullable<short> ChequeBookSize { get; set; }
        public Nullable<int> LastChequeNum { get; set; }
        public string ChequeBookOrdered { get; set; }
        public string DepositBookOrdered { get; set; }
        public string ProdBSB { get; set; }
        public string PowerType { get; set; }
        public string FISFlag { get; set; }
        public Nullable<int> ASFRejectionCounted { get; set; }
        public string PrintFlag { get; set; }
        public string ReportTypes { get; set; }
        public string DebitCardOrdered { get; set; }
        public Nullable<decimal> PersonalContrib { get; set; }
        public Nullable<decimal> EmployerContrib { get; set; }
        public Nullable<decimal> SalarySacrifice { get; set; }
        public Nullable<decimal> SpouseContrib { get; set; }
        public Nullable<decimal> PersonalContribTaxDeduction { get; set; }
        public string Indexation { get; set; }
        public Nullable<double> IndexationRate { get; set; }
        public string CommissionOption { get; set; }
        public int RCV { get; set; }
        public Nullable<int> Term { get; set; }
        public string TermType { get; set; }
        public int GuaranteedTerm { get; set; }
        public decimal JointAnnuitantDecreasePerc { get; set; }
        public bool CompliantFlag { get; set; }
        public bool ETPFlag { get; set; }
        public Nullable<bool> IsServicePensionAge { get; set; }
        public string PaymentFreq { get; set; }
        public string PaymentType { get; set; }
        public decimal AnnualIntRatePerc { get; set; }
        public Nullable<decimal> AnnualPaymentAmt { get; set; }
        public string QuoteNo { get; set; }
        public Nullable<double> RelevantNo { get; set; }
        public Nullable<decimal> UnDeductPP { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<System.DateTime> NextPayDate { get; set; }
        public Nullable<System.DateTime> NextReviewDate { get; set; }
        public Nullable<decimal> NextPaymentAmt { get; set; }
        public Nullable<System.DateTime> InitialReviewDate { get; set; }
        public Nullable<decimal> AnnualDeductibleAmt { get; set; }
        public bool CommutableFlag { get; set; }
        public string BadgeId { get; set; }
        public bool ReturnMail { get; set; }
        public Nullable<double> GuarEarnRateWithoutInflation { get; set; }
        public string ExtensionOfPolicy { get; set; }
        public bool ContinuityCertReturned { get; set; }
        public Nullable<decimal> DeductibleAdjustmentAmt { get; set; }
        public string ExternalNo3 { get; set; }
        public Nullable<decimal> IncomeAdjustmentAmt { get; set; }
        public Nullable<int> InvestFacility { get; set; }
    }
}
