//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_MVC5Bootstrap_Intellivue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAccountInvOpt
    {
        public string AcctNo { get; set; }
        public int ProdNo { get; set; }
        public Nullable<int> ParentProdNo { get; set; }
        public decimal Unit { get; set; }
        public string DistMethod { get; set; }
        public Nullable<System.DateTime> LastDistDate { get; set; }
        public Nullable<decimal> SavingPlanAmt { get; set; }
        public string SavingPlanFreq { get; set; }
        public Nullable<System.DateTime> SavingPlanStartDate { get; set; }
        public Nullable<System.DateTime> SavingPlanNextDate { get; set; }
        public Nullable<decimal> AutoCashAmt { get; set; }
        public string AutoCashFreq { get; set; }
        public Nullable<System.DateTime> AutoCashStartDate { get; set; }
        public Nullable<System.DateTime> AutoCashNextDate { get; set; }
        public string ChequeBookReq { get; set; }
        public string DepositBookReq { get; set; }
        public Nullable<decimal> NPRPerc { get; set; }
        public Nullable<System.DateTime> DateLastChanged { get; set; }
        public Nullable<decimal> TrailRate { get; set; }
        public string MgmtFeeRebateType { get; set; }
        public Nullable<double> MgmtFeeRebateRate { get; set; }
        public string MgmtFeeRebateCode { get; set; }
        public string MgmtFeePaymentMethod { get; set; }
        public Nullable<System.DateTime> MgmtFeeEffectiveDate { get; set; }
        public string NPRMgr { get; set; }
        public Nullable<decimal> NPRMonthlyPymtAmt { get; set; }
        public Nullable<System.DateTime> NPRLastReviewDate { get; set; }
        public Nullable<decimal> FISPerc { get; set; }
        public Nullable<decimal> PercApplFee { get; set; }
        public Nullable<decimal> DollarApplFee { get; set; }
        public Nullable<decimal> PercASFFee { get; set; }
        public Nullable<decimal> AccruedInterest { get; set; }
        public Nullable<decimal> TrailRebateRate { get; set; }
        public Nullable<System.DateTime> RSPExpiryDate { get; set; }
        public Nullable<System.DateTime> ACExpiryDate { get; set; }
    }
}
