//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_MVC5Bootstrap_Intellivue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerAccount
    {
        public string CustID { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string AcctNo { get; set; }
        public int ProdNo { get; set; }
        public string TaxFileNo { get; set; }
        public string TFNStatus { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateTFN { get; set; }
        public string PrimaryOwnerFlag { get; set; }
        public string RelationshipCode { get; set; }
        public string SignatoryFlag { get; set; }
        public Nullable<System.DateTime> DateLastChanged { get; set; }
        public string ABN { get; set; }
        public string TaxExemptCode { get; set; }
        public Nullable<System.DateTime> ChildDOB { get; set; }
        public Nullable<System.DateTime> NonResidentFromDate { get; set; }
        public Nullable<System.DateTime> NonResidentToDate { get; set; }
        public string ExmptTaxSec128B { get; set; }
        public string TrusteeCapacity { get; set; }
        public string ExmptOtherIncomeTaxSec23 { get; set; }
        public string ExmptOtherIncomeIntOrg { get; set; }
        public string ResidentCode { get; set; }
        public string ResidentCountrycode { get; set; }
        public string ABNStatus { get; set; }
        public string ProdBSB { get; set; }
        public Nullable<decimal> TaxRebateAmt { get; set; }
        public string ClaimTaxFreeFlag { get; set; }
        public string TFNExemptReason { get; set; }
        public string TFNPermission { get; set; }
        public string AustResTaxFlag { get; set; }
        public Nullable<double> FlatTaxRate { get; set; }
        public Nullable<System.DateTime> FlatRateExpDate { get; set; }
        public string TaxExemptFlag { get; set; }
        public string ClaimETPRebateFlag { get; set; }
        public string ETPReasonCode { get; set; }
        public string SATOFlag { get; set; }
        public string SATOCat { get; set; }
        public string MedicareExemptType { get; set; }
        public Nullable<double> ETPRebateProportion { get; set; }
        public bool DeductibleAmt { get; set; }
        public bool FamilyTaxBenefit { get; set; }
        public bool FinSupplementDebt { get; set; }
        public bool HECS { get; set; }
        public bool SpecRebates { get; set; }
        public string PayBasis { get; set; }
        public Nullable<decimal> RebatableProportion { get; set; }
    }
}
