//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_MVC5Bootstrap_Intellivue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCode
    {
        public string CodeType { get; set; }
        public string Code { get; set; }
        public string CodeDesc { get; set; }
        public string CodeReportShortDesc { get; set; }
        public string CodeSensivity { get; set; }
        public string CodeDisplaySeq { get; set; }
        public string CodeDisplaySeqNo { get; set; }
        public string CodeDefValue { get; set; }
        public Nullable<int> CodeLength { get; set; }
        public string LoadType { get; set; }
        public string CodeSeverity { get; set; }
    }
}
