//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_MVC5Bootstrap_Intellivue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountryPostCode
    {
        public string CountryCode { get; set; }
        public string Postcode { get; set; }
        public string Locality { get; set; }
        public string State { get; set; }
        public string Comments { get; set; }
        public string DeliveryOffice { get; set; }
        public string PresortIndicator { get; set; }
        public string ParcelZone { get; set; }
        public string BSPnumber { get; set; }
        public string BSPname { get; set; }
        public string Category { get; set; }
    }
}
