//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_MVC5Bootstrap_Intellivue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public string CustID { get; set; }
        public string ExternalID1 { get; set; }
        public string ExternalID2 { get; set; }
        public string CustName { get; set; }
        public string CustGivenName { get; set; }
        public string CustCategory { get; set; }
        public string CustTitle { get; set; }
        public string CustType { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<System.DateTime> DateLastChanged { get; set; }
        public Nullable<System.DateTime> DateofProbate { get; set; }
        public Nullable<System.DateTime> DateofDealth { get; set; }
        public string SourceCode { get; set; }
        public string BlockCode { get; set; }
        public string StatusFlag { get; set; }
        public string HomeTel { get; set; }
        public string WorkTel { get; set; }
        public string HomeFax { get; set; }
        public string WorkFax { get; set; }
        public string MobileNo { get; set; }
        public string EmailAddr1 { get; set; }
        public string EmailAddr2 { get; set; }
        public string Addrline1 { get; set; }
        public string Addrline2 { get; set; }
        public string Addrline3 { get; set; }
        public string Addrline4 { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string CountryCode { get; set; }
        public string MailingName { get; set; }
        public string CorrName { get; set; }
        public string ResidentCode { get; set; }
        public string ResidentCountryCode { get; set; }
        public string FileNote { get; set; }
        public string ABN { get; set; }
        public Nullable<int> TempOrderNo { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DeceasedDate { get; set; }
        public bool ReturnMail { get; set; }
        public string IsServicePensionAge { get; set; }
        public Nullable<System.DateTime> DeathNotifiedOn { get; set; }
    }
}
