//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_MVC5Bootstrap_Intellivue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductTotal
    {
        public int ProdNo { get; set; }
        public int ParentProdNo { get; set; }
        public string ProcessType { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<decimal> ApplGrossAmt { get; set; }
        public Nullable<decimal> ApplFeeAmt { get; set; }
        public Nullable<decimal> ApplRebateAmt { get; set; }
        public Nullable<decimal> ApplNetAmt { get; set; }
        public Nullable<int> ApplCount { get; set; }
        public Nullable<decimal> ApplUnits { get; set; }
        public Nullable<decimal> RdmGrossAmt { get; set; }
        public Nullable<decimal> RdmNetAmt { get; set; }
        public Nullable<int> RdmCount { get; set; }
        public Nullable<decimal> RdmUnits { get; set; }
        public Nullable<decimal> SwitchInGrossAmt { get; set; }
        public Nullable<decimal> SwitchInFeeAmt { get; set; }
        public Nullable<decimal> SwitchInRebateAmt { get; set; }
        public Nullable<decimal> SwitchInNetAmt { get; set; }
        public Nullable<decimal> SwitchInCount { get; set; }
        public Nullable<decimal> SwitchInUnits { get; set; }
        public Nullable<decimal> SwitchOutGrossAmt { get; set; }
        public Nullable<decimal> SwitchOutNetAmt { get; set; }
        public Nullable<int> SwitchOutCount { get; set; }
        public Nullable<decimal> SwitchOutUnits { get; set; }
        public Nullable<decimal> TotalUnits { get; set; }
        public Nullable<double> ApplTfnTax { get; set; }
        public Nullable<double> ApplWHTax { get; set; }
        public Nullable<decimal> chqGrossAmt { get; set; }
        public Nullable<double> chqFeeAmt { get; set; }
        public Nullable<double> ChqRebateAmt { get; set; }
        public Nullable<double> ChqNetAmt { get; set; }
        public Nullable<int> ChqCount { get; set; }
        public Nullable<double> chqTfnTax { get; set; }
        public Nullable<double> chqWHTax { get; set; }
        public Nullable<decimal> DESGrossAmt { get; set; }
        public Nullable<double> DESFeeAmt { get; set; }
        public Nullable<double> DESRebateAmt { get; set; }
        public Nullable<double> DESNetAmt { get; set; }
        public Nullable<int> DESCount { get; set; }
        public Nullable<double> DESTfnTax { get; set; }
        public Nullable<double> DESWHTax { get; set; }
        public Nullable<decimal> TotalGrossAmt { get; set; }
        public Nullable<double> TotalFeeAmt { get; set; }
        public Nullable<double> TotalRebateAmt { get; set; }
        public Nullable<double> TotalNetAmt { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public Nullable<double> TotaltfnTax { get; set; }
        public Nullable<double> TotalWHTax { get; set; }
        public Nullable<decimal> GSTAmt { get; set; }
        public Nullable<double> chqGSTAmt { get; set; }
        public Nullable<double> DESGSTAmt { get; set; }
        public Nullable<double> TotalGSTAmt { get; set; }
        public Nullable<double> PoolIssuePrice { get; set; }
        public Nullable<double> PoolRdmPrice { get; set; }
        public Nullable<double> PoolApplUnits { get; set; }
        public Nullable<double> PoolRdmUnits { get; set; }
        public Nullable<double> PoolRdmAmt { get; set; }
        public Nullable<double> PoolApplAmt { get; set; }
        public Nullable<double> PoolUnits { get; set; }
        public Nullable<decimal> PoolNetAmt { get; set; }
        public Nullable<double> PoolABOTD { get; set; }
        public string TotalType { get; set; }
        public Nullable<double> PoolMIDPrice { get; set; }
        public Nullable<double> PoolMIDApplUnits { get; set; }
        public Nullable<double> PoolMIDRdmUnits { get; set; }
        public Nullable<double> PoolMIDRdmAmt { get; set; }
        public Nullable<double> PoolMIDApplAmt { get; set; }
        public string FileNote { get; set; }
        public string StatusFlag { get; set; }
        public string InputUserID { get; set; }
        public Nullable<System.DateTime> InputDateTime { get; set; }
        public string VerifyUserID { get; set; }
        public Nullable<System.DateTime> VerifyDatetime { get; set; }
        public Nullable<System.DateTime> ValuationDate { get; set; }
        public string InterestPaid { get; set; }
        public Nullable<long> ActiveAccounts { get; set; }
        public Nullable<decimal> InterFundTotalUnits { get; set; }
    }
}
