//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_MVC5Bootstrap_Intellivue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int ProdNo { get; set; }
        public int ParentProdNo { get; set; }
        public string ProdGroup { get; set; }
        public string ProdName { get; set; }
        public string ProdShortName { get; set; }
        public string ProdType { get; set; }
        public Nullable<System.DateTime> ProdIntroDate { get; set; }
        public Nullable<System.DateTime> ProdCloseDate { get; set; }
        public string HasChildNode { get; set; }
        public string DistFreq { get; set; }
        public string StmtFreq { get; set; }
        public string TelWithdrawal { get; set; }
        public string TelDeposit { get; set; }
        public string TelSwitching { get; set; }
        public string TrailFreq { get; set; }
        public string CommFreq { get; set; }
        public string SavingPlanFreq { get; set; }
        public string AutoCashFreq { get; set; }
        public string DistMethod { get; set; }
        public string StatusFlag { get; set; }
        public string APIR { get; set; }
        public string ABN { get; set; }
        public string ARSN { get; set; }
        public string CurrencyCode { get; set; }
        public string DepBook { get; set; }
        public string ChqBook { get; set; }
        public string NPR { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> LastChangedDate { get; set; }
        public Nullable<short> ChqBookSize { get; set; }
        public Nullable<short> DepBookSize { get; set; }
        public Nullable<short> InputSeqNo { get; set; }
        public Nullable<short> ReportSeqNo { get; set; }
        public Nullable<short> WithdrawalSeqNo { get; set; }
        public string LinktoPool { get; set; }
        public Nullable<int> PoolProdNo { get; set; }
        public Nullable<int> AcctProdNo { get; set; }
        public Nullable<int> ChildLevel { get; set; }
        public string Mnemonic { get; set; }
        public string BankAcctName { get; set; }
        public string BankAcctNo { get; set; }
        public string BSB { get; set; }
        public string BankName { get; set; }
        public string CRName { get; set; }
        public string CRNo { get; set; }
        public string DBName { get; set; }
        public string DBNo { get; set; }
        public string DBBankAcctName { get; set; }
        public string DBBankAcctNo { get; set; }
        public string DBBSB { get; set; }
        public string DBBankName { get; set; }
        public string AdvDBName { get; set; }
        public string AdvDBNo { get; set; }
        public string AdvDBBankAcctName { get; set; }
        public string AdvDBBSB { get; set; }
        public string AdvDBBankAcctNo { get; set; }
        public string AdvDBBankName { get; set; }
        public Nullable<System.DateTime> ProdClosetoNewDate { get; set; }
        public string TFNRequired { get; set; }
        public string MgmtFeeFreq { get; set; }
        public string InterfaceCode { get; set; }
        public string InterfaceDesc { get; set; }
        public string SavingPlan { get; set; }
        public string AutoCash { get; set; }
        public string DateOfBirthRequired { get; set; }
        public string InsuranceOffered { get; set; }
        public string ResEntityName { get; set; }
        public string TrustFullName { get; set; }
        public string ACN { get; set; }
        public string ContactName { get; set; }
        public string AddrLine1 { get; set; }
        public string AddrLine2 { get; set; }
        public string AddrLine3 { get; set; }
        public string AddrLine4 { get; set; }
        public string Suburb { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public string CountryCode { get; set; }
        public string ContactNumber { get; set; }
        public string Fax { get; set; }
        public string EmailAddress { get; set; }
        public string ReturnMedia { get; set; }
        public string ProdBSB { get; set; }
        public string PfolioFamily { get; set; }
        public string AdvSerFeeFreq { get; set; }
        public Nullable<System.DateTime> MPLastRunDate { get; set; }
        public Nullable<System.DateTime> IPDLastRunDate { get; set; }
        public string ATOMnemonic { get; set; }
        public Nullable<System.DateTime> ICLastRunDate { get; set; }
        public Nullable<System.DateTime> SRLastRunDate { get; set; }
        public string AccountPrefixActive { get; set; }
        public string AccountPrefixUsed { get; set; }
        public string AccountPrefixNext { get; set; }
        public Nullable<int> ASFSeqNo { get; set; }
        public string ASFGSTType { get; set; }
        public string SFN { get; set; }
        public string RSPIndexation { get; set; }
        public string CNTTaxProcFreq { get; set; }
        public string WHDTaxProcFreq { get; set; }
        public string LMPTaxProcFreq { get; set; }
        public Nullable<System.DateTime> CNTTaxNextProcDate { get; set; }
        public Nullable<System.DateTime> WHDTaxNextProcdate { get; set; }
        public Nullable<System.DateTime> LMPTaxNextProcDate { get; set; }
        public string TFN { get; set; }
        public string BranchNumber { get; set; }
        public string ContactJobTitle { get; set; }
        public string GenderRequired { get; set; }
    }
}
