//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_MVC5Bootstrap_Intellivue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public string AcctNo { get; set; }
        public int ProdNo { get; set; }
        public long Tranid { get; set; }
        public Nullable<System.DateTime> BankingDate { get; set; }
        public Nullable<int> TranType { get; set; }
        public string TranDesc { get; set; }
        public string SubTranDesc { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Units { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<decimal> ABOTD { get; set; }
        public string RequestType { get; set; }
        public string StatusFlag { get; set; }
        public Nullable<long> RootTranID { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public Nullable<decimal> ApplFeeAmt { get; set; }
        public Nullable<decimal> ApplfeePerc { get; set; }
        public Nullable<decimal> CommPerc { get; set; }
        public Nullable<decimal> CommAmt { get; set; }
        public Nullable<decimal> TrailPerc { get; set; }
        public Nullable<System.DateTime> ValuationDate { get; set; }
        public Nullable<System.DateTime> SpecialValuationDate { get; set; }
        public string PrintFlag { get; set; }
        public string PrintMethod { get; set; }
        public Nullable<short> PrintNo { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string CCPrintFlag { get; set; }
        public string CCPrintMethod { get; set; }
        public Nullable<short> CCPrintNo { get; set; }
        public Nullable<System.DateTime> CCPrintDate { get; set; }
        public string CustNo { get; set; }
        public string Source { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> LastChangedDate { get; set; }
        public Nullable<decimal> AmountPerc { get; set; }
        public Nullable<decimal> RequestValue { get; set; }
        public string ExtRef1 { get; set; }
        public string ExtRef2 { get; set; }
        public string ExtRef3 { get; set; }
        public string DistMethod { get; set; }
        public Nullable<decimal> FID { get; set; }
        public Nullable<decimal> TFNTax { get; set; }
        public Nullable<decimal> WHTax { get; set; }
        public Nullable<decimal> RebateAmt { get; set; }
        public Nullable<decimal> RebatePerc { get; set; }
        public string ProcessID { get; set; }
        public string ProcessType { get; set; }
        public string TranNote { get; set; }
        public string BalanceFlag { get; set; }
        public string PricingMethod { get; set; }
        public string TranNote1 { get; set; }
        public string TranNote2 { get; set; }
        public Nullable<decimal> GSTAmt { get; set; }
        public Nullable<decimal> MgmtFeeRebateAmt { get; set; }
        public string MgmtFeeRebateCode { get; set; }
        public Nullable<System.DateTime> ProcessEndDate { get; set; }
        public Nullable<System.DateTime> ProcessStartDate { get; set; }
        public string NonCashFlag { get; set; }
        public string Campaign { get; set; }
        public string AdviserRef { get; set; }
        public Nullable<double> CostUnitsAllocated { get; set; }
        public Nullable<decimal> CGTAmt { get; set; }
        public string CGTProcessID { get; set; }
        public Nullable<decimal> TaxFreeAmt { get; set; }
        public Nullable<decimal> TaxdeferredAmt { get; set; }
        public Nullable<decimal> TaxExemption { get; set; }
        public Nullable<decimal> ReturnofCapital { get; set; }
        public Nullable<decimal> PAYETaxAmt { get; set; }
        public Nullable<decimal> PAYGTaxAmt { get; set; }
        public Nullable<decimal> ContTaxAmt { get; set; }
        public Nullable<decimal> ExitFeeAmt { get; set; }
        public string FISFlag { get; set; }
        public Nullable<decimal> IndexedCostAmt { get; set; }
        public Nullable<System.DateTime> LastIndexedDate { get; set; }
        public Nullable<long> TranIDRef { get; set; }
        public string ACCTNORef { get; set; }
        public string ExitFeeRequestType { get; set; }
        public Nullable<decimal> RedeemableAmt { get; set; }
        public Nullable<long> RelatedTranID { get; set; }
        public Nullable<System.DateTime> TaxPaid { get; set; }
        public Nullable<decimal> UpfrontRebateAmt { get; set; }
        public string InputUserID { get; set; }
        public string AuthoriseUserID { get; set; }
        public Nullable<System.DateTime> authorisedatetime { get; set; }
        public Nullable<decimal> DeductibleAmt { get; set; }
        public Nullable<decimal> DeductibleAmtAvail { get; set; }
    }
}
