//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITL_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public string SysId { get; set; }
        public string TableRef { get; set; }
        public string ColumnName { get; set; }
        public string Type { get; set; }
        public string Reference { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<int> Display { get; set; }
        public string ColumnLabel { get; set; }
        public Nullable<int> Mandatory { get; set; }
        public Nullable<int> MaxLength { get; set; }
        public Nullable<int> ReadOnly { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
